import { CheckCircle2, AlertTriangle } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { PredictionResult } from '@workspace/api-client-react';

interface VerdictDisplayProps {
  result: PredictionResult;
}

export function VerdictDisplay({ result }: VerdictDisplayProps) {
  const isReal = result.label === 'Real';
  const confidencePercent = (result.confidence * 100).toFixed(1);

  return (
    <div className="space-y-6 animate-verdict-reveal" data-testid="verdict-display">
      {/* Verdict Header */}
      <div className="flex items-center gap-4 p-6 rounded-lg border-2 bg-card"
        style={{
          borderColor: isReal ? 'hsl(var(--accent))' : 'hsl(var(--destructive))',
        }}
      >
        <div className={cn(
          'w-12 h-12 rounded-full flex items-center justify-center',
          isReal ? 'bg-accent/10' : 'bg-destructive/10'
        )}>
          {isReal ? (
            <CheckCircle2 className="w-7 h-7 text-accent" />
          ) : (
            <AlertTriangle className="w-7 h-7 text-destructive" />
          )}
        </div>
        <div className="flex-1">
          <p className="text-sm font-mono text-muted-foreground uppercase tracking-wide mb-1">
            Verdict
          </p>
          <p className={cn(
            'text-2xl font-bold',
            isReal ? 'text-accent' : 'text-destructive'
          )}
          data-testid="text-verdict-label"
          >
            {result.label}
          </p>
        </div>
        <div className="text-right">
          <p className="text-sm font-mono text-muted-foreground uppercase tracking-wide mb-1">
            Confidence
          </p>
          <p className="text-2xl font-bold font-mono" data-testid="text-confidence">
            {confidencePercent}%
          </p>
        </div>
      </div>

      {/* Probability Breakdown */}
      <div className="space-y-4">
        <h4 className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
          Model Output
        </h4>
        
        {/* Real probability bar */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-sm font-mono text-foreground">Real</span>
            <span className="text-sm font-mono font-medium" data-testid="text-prob-real">
              {(result.probReal * 100).toFixed(2)}%
            </span>
          </div>
          <div className="h-3 bg-muted rounded-full overflow-hidden">
            <div
              className="h-full bg-accent transition-all duration-500 ease-out"
              style={{ width: `${result.probReal * 100}%` }}
            />
          </div>
        </div>

        {/* AI-Generated probability bar */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-sm font-mono text-foreground">AI-Generated</span>
            <span className="text-sm font-mono font-medium" data-testid="text-prob-ai">
              {(result.probAiGenerated * 100).toFixed(2)}%
            </span>
          </div>
          <div className="h-3 bg-muted rounded-full overflow-hidden">
            <div
              className="h-full bg-destructive transition-all duration-500 ease-out"
              style={{ width: `${result.probAiGenerated * 100}%` }}
            />
          </div>
        </div>
      </div>

      {/* Technical note */}
      <div className="p-4 bg-muted/50 rounded-lg border border-border">
        <p className="text-xs text-muted-foreground leading-relaxed">
          This prediction is generated by a convolutional neural network trained on
          deepfake detection datasets. Confidence represents the model's certainty in
          its classification (range: 0.5–1.0).
        </p>
      </div>
    </div>
  );
}
